language: java
jdk:
  - openjdk7
  - oraclejdk8

sudo: false
env:
  global:
    - JAVA7_HOME="/usr/lib/jvm/java-7-oracle"

cache:
  directories:
    - $HOME/.m2

notifications:
  email: false

before_install:
  - ulimit -u 65535

script:
  - ./gradlew test

branches:
  except:
    - /.*\/.*/

